### PR TITLE
Create a_texture_pos attribute in sdf shader 

### PR DESCRIPTION
**Pull request by xrwang**
Update name of a_data1 to a_texture_pos, for sdfs.

ref: https://github.com/mapbox/mapbox-gl-js/pull/2930

cc @lucaswoj @amyleew

### CODE REVIEW

**Comment by amyleew** [comment]
@brunoabinader - Can you take a look at this PR and see if it's ready to merge?

/cc @lucaswoj @xrwang

**Comment by xrwang** [comment]
thank you for reviewing and 👻  guiding @lbud! updated per your comments.

**Comment by lucaswoj** [comment]
Pushing a squash and rebase, previous HEAD was 2b1074e600aa9dbe3d80b18bf17032883012ad7d

**Comment by brunoabinader** [comment]
Awesome @xrwang, @amyleew!

**Pull request merged**
